NETWORK_MAPPING = {
    "Ethereum": 'EthereumMainnet',
    'Zora': 'ZoraMainnet',
    'Blast': 'BlastMainnet',
    'OpBNB': 'OpbnbMainnet',
    'Polygon': 'PolygonPoSMainnet',
    "Arbitrum": "ArbitrumOneMainnet",
    "BSC": "BnbMainnet",
    "Optimism": "OptimismMainnet",
    "ZKSync": "ZksyncMainnet",
    "Base": "BaseMainnet",
    "Metis": "MetisMainnet",
    "Linea": "LineaMainnet",
    "Scroll": "ScrollMainnet",
}
